# Generated by Django 6.0.3 on 2026-03-11 19:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('source_type', models.CharField(choices=[('local_upload', 'Local Upload'), ('url_upload', 'Url Upload')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('auto_annotation_interval', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('frame', 'Frame'), ('timestamp', 'Timestamp')], max_length=20)),
                ('frame_number', models.IntegerField(blank=True, help_text='Set when type=frame', null=True)),
                ('timestamp', models.FloatField(blank=True, help_text='Seconds into video, set when type=timestamp', null=True)),
                ('content', models.TextField(help_text='Annotation text/data')),
                ('note', models.TextField(blank=True, help_text='Optional note', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.video')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
