# Generated by Django 6.0.3 on 2026-03-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['timestamp', 'frame_number', 'created_at']},
        ),
        migrations.AddField(
            model_name='annotation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Annotation text/data'),
        ),
    ]
