# Generated by Django 6.0.3 on 2026-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_annotation_options_annotation_source_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['video', 'source'], name='idx_annotation_video_source'),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['video', 'source', 'timestamp'], name='idx_annotation_video_src_ts'),
        ),
    ]
