# Generated by Django 6.0.3 on 2026-03-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_annotation_idx_annotation_video_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='note',
        ),
    ]
