# Generated by Django 6.0.3 on 2026-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_annotation_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['timestamp', 'timestamp_start', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='frame_number',
        ),
        migrations.AddField(
            model_name='annotation',
            name='timestamp_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='timestamp_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['video', 'source', 'timestamp_start'], name='idx_annotation_video_src_ts_start'),
        ),
    ]
