# Generated by Django 6.0.3 on 2026-03-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_annotation_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='annotation',
            new_name='idx_ann_video_src_ts_start',
            old_name='idx_annotation_video_src_ts_start',
        ),
    ]
